name: Terraform AWS Workflow for Node application
on: push
env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
jobs:
  tf_build:
    name: Terraform validation and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout terraform code to container
        uses: actions/checkout@v4
        with:
          repository: kesaripatil/ecr-nodejsapp-terraform-poc

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init, plan and apply
        run: |
          echo `pwd`
          echo "********** Running Terraform Init **********"
          terraform init -backend-config="bucket=$BUCKET_TF_STATE"

          echo "********** Running Terraform Validate ***********"
          terraform validate

          echo "********** Running Terraform Destroy ************"
          terraform destroy -auto-approve
#
#          echo "********** Running Terraform Plan *************"
#          terraform plan
#
#          echo "********** Running Terraform Apply ************"
#          terraform apply -auto-approve